### ISSUE TITLE
IPhone no sound with midi player WP site

### ISSUE THREAD

**Issue by KetanPate** [cifkao/html-midi-player#32] opened 2021-09-23 05:48 UTC
I have used your plugin but the sound not coming on the player.
player play but without sound on Ipad and iPhone X.

We have a check on the device iPhone 8 Plus, iPhone SE 2, iOS version: 14.6 and 14.7 both.
Also, We have checked Ipad with IOS version 12 so it's working on it but still an issue on Iphone X.

**Comment by majorcyto** [comment] 2021-09-23 06:56
It does work on iPhone and iPad for me without issue. 

The only thing I noticed is that you need to make sure the silence button is not enabled on the side of the phone.

**Comment by cifkao** [comment] 2021-09-23 07:14
Duplicate of #28?

**Closed** 2021-09-23 10:05 UTC
